// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"HIME_DisableDashing","status":true,"description":"v1.0 - Allows you to disable dashing using events","parameters":{}},
{"name":"HIME_SelfVariables","status":true,"description":"v1.4 - Allows you to create and manage self-variables for all\r\nof your events!","parameters":{}},
{"name":"HIME_CustomPageConditions","status":true,"description":"v1.6 - Create your own page conditions for your events using\r\nregular eventing!","parameters":{}}
];
